name: zoom_view
description: "zoom and scroll a ListView or other Scrollables like scrollable_positioned_list"
version: 1.0.1
repository: "https://github.com/yakagami/zoom_view"

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
